### PR TITLE
Add clickhouse support

### PR DESCRIPTION
**Pull request by ed-RG**
Adds clickhouse support from public repo

### CODE REVIEW

**Review by Barry-RG — APPROVED** [review]

**Comment by sazonov** [comment]
@Barry-RG Hello. Could you please tell the purpose of this clone to my PR #3611?

**Comment by Barry-RG** [comment]
Hi @sazonov apologies for the lack of information on this. As you are probably very aware from your own PR, Flyway has an issue in regards to its lead time in merging PRs from the community. This is due to a hardcoded build mechanism that allows us to deploy to flyway/flyway which has been there since Flyway's early releases which we have not been able to move away. Over the last couple of year especially, the use of this system has become a hindrance and prevented us from interacting with our open source PRs in the way that we would wish. As a result, we are looking at ways to break away from this in a method which does not disrupt Flyway development. 
This repository is one of those ways, since database contributions are normally the most self contained. Currently this is in early stages, so we are not encouraging PRs here just yet. We do not want to be in a situation of saying "Your PRs are getting ignored over there, port them over here so that can continue to get ignored while we sort this out".
We are hopeful that once the pipeline with this repository is complete, we can use this as a repository to encourage and improve our relationship with the open source community and contributions. 

In regards to your specific PR, it was one of the most clear to use as an experiment for this repository. However, I can see that there was some miscommunication and your git authorship was not transferred over. I will help work on fixing that if that would satisfy you.

**Comment by sazonov** [comment]
@Barry-RG thank you for the answer. I'm not the only author to this PR, so I think the authorship of all members must be saved. Second thing is that changes to my PR are still being made and those changes need to be merged to main branch.

**Comment by sazonov** [comment]
@Barry-RG could you please tell if there are any updates on this?

**Comment by Barry-RG** [comment]
@sazonov we have reimported your PR as and squashed the history in to this repository.

**Comment by sazonov** [comment]
@Barry-RG, thanks!

**Pull request merged**
